#!/usr/bin/env python3
"""Render CONFORMANCE.md from model/ids.toml and check the bijection.

Mirrors the PrismPM discipline: one id, one scenario, one test. Run with
--check to verify without writing. Exit 1 on any violation.
"""
from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = (
    "<!-- @generated by `just model-write` from model/ids.toml. -->\n"
    "<!-- Do not edit: model/*.toml is the source of truth. -->\n\n"
    "# CONFORMANCE\n\n"
    "Every registered id has exactly one Gherkin scenario and exactly one executable test named `conformance_<id>`.\n\n"
    "| ID | Level | Suite | Statement |\n| --- | --- | --- | --- |\n"
)
FOOTER = (
    "\n## Evidence levels\n\n"
    "- `some-true`: a fact reproduced from an authority. Not established here.\n"
    "- `build`: constructed here and validated against its oracle. Evidence, not a proof.\n"
    "- `open`: measured and reported. Never asserted.\n"
)


def load(path: Path) -> dict:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def scenarios(suite_dir: Path) -> dict[str, tuple[str, str, str]]:
    found: dict[str, tuple[str, str, str]] = {}
    for feature in sorted(suite_dir.glob("*.feature")):
        lines = feature.read_text(encoding="utf-8").splitlines()
        for index, line in enumerate(lines):
            tags = line.strip().split()
            if not tags or not tags[0].startswith("@"):
                continue
            if len(tags) != 2:
                raise SystemExit(f"FAIL {feature.name}:{index + 1}: tag line must be exactly `@<ID> @<level>`")
            if index + 1 >= len(lines) or not lines[index + 1].strip().startswith("Scenario:"):
                raise SystemExit(f"FAIL {feature.name}:{index + 1}: tag line must be followed by Scenario:")
            statement = lines[index + 1].strip()[len("Scenario:"):].strip()
            identifier = tags[0][1:]
            if identifier in found:
                raise SystemExit(f"FAIL {identifier} has more than one scenario")
            found[identifier] = (feature.stem, tags[1][1:], statement)
    return found


def tests(root: Path) -> set[str]:
    names: set[str] = set()
    pattern = re.compile(r"fn (conformance_[a-z0-9_]+)\s*\(")
    for source in list(root.glob("tests/*.rs")) + list(root.glob("tests/*.py")):
        names.update(pattern.findall(source.read_text(encoding="utf-8")))
    return names


def main(check_only: bool) -> int:
    ids = load(ROOT / "model" / "ids.toml").get("id", [])
    ledger = load(ROOT / "model" / "ledger.toml").get("claim", [])
    failures: list[str] = []

    for claim in ledger:
        if claim["level"] == "some-true" and not claim.get("authority"):
            failures.append(f"{claim['id']}: some-true claim must name an authority")
        if claim["level"] == "build" and claim.get("authority"):
            failures.append(f"{claim['id']}: build claim must not name an authority")

    found = scenarios(ROOT / "features" / "suites")
    present = tests(ROOT)
    for row in ids:
        identifier = row["id"]
        scenario = found.get(identifier)
        if scenario is None:
            failures.append(f"{identifier}: no scenario")
            continue
        suite, level, statement = scenario
        if suite != row["suite"]:
            failures.append(f"{identifier}: scenario lives in {suite}.feature, register says {row['suite']}")
        if level != row["level"]:
            failures.append(f"{identifier}: scenario tagged @{level}, register says {row['level']}")
        if statement != row["statement"]:
            failures.append(f"{identifier}: scenario statement differs from register")
        expected = "conformance_" + identifier.lower().replace("-", "_")
        if expected not in present:
            failures.append(f"{identifier}: no test named {expected}")
    for identifier in found:
        if identifier not in {row["id"] for row in ids}:
            failures.append(f"{identifier}: scenario has no register row")

    rendered = HEADER
    for row in ids:
        rendered += f"| `{row['id']}` | `{row['level']}` | `{row['suite']}` | {row['statement']} |\n"
    if ledger:
        rendered += "\n## Claims that are not conformance ids\n\n| ID | Level | Statement | Authority |\n| --- | --- | --- | --- |\n"
        for claim in ledger:
            rendered += f"| `{claim['id']}` | `{claim['level']}` | {claim['statement']} | {claim.get('authority', '')} |\n"
    rendered += FOOTER

    target = ROOT / "CONFORMANCE.md"
    if check_only:
        if not target.exists() or target.read_text(encoding="utf-8") != rendered:
            failures.append("CONFORMANCE.md is stale, run `just model-write`")
    else:
        target.write_text(rendered, encoding="utf-8")

    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        return 1
    print(f"ok: {len(ids)} ids, {len(ledger)} ledger claims, bijection holds")
    return 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv))
